CREATE SEQUENCE CTS_OT_ACTIVIDAD START WITH 100 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE CTS_OT_RULE_INCIDENT START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE TABLE CT_TAREA (ID_TAREA NUMBER(19) PRIMARY KEY, CODIGO VARCHAR2(255) NOT NULL);
CREATE TABLE CT_ACTIVIDAD (ID_ACTIVIDAD NUMBER(19) PRIMARY KEY, CODIGO VARCHAR2(255) UNIQUE,
 CATEGORIA VARCHAR2(255), ACTIVO CHAR(1));
CREATE TABLE CT_REGLA_TIPO (ID_REGLA_TIPO NUMBER(19) PRIMARY KEY, NOMBRE_CORTO VARCHAR2(255) UNIQUE);
CREATE TABLE CT_REGLA (ID_REGLA NUMBER(19) PRIMARY KEY, NOMBRE VARCHAR2(255) UNIQUE NOT NULL);
CREATE TABLE CT_ORDEN_TRABAJO (ID_ORDEN_TRABAJO NUMBER(19) PRIMARY KEY, NRO_OT VARCHAR2(255) UNIQUE,
 TIPO_OT CHAR(1), ID_TAREA NUMBER(19) REFERENCES CT_TAREA(ID_TAREA));
CREATE TABLE CT_OT_ACTIVIDAD (ID_OT_ACTIVIDAD NUMBER(19) PRIMARY KEY, ACTIVO CHAR(1), CANTIDAD NUMBER(10),
 ID_ACTIVIDAD NUMBER(19) REFERENCES CT_ACTIVIDAD(ID_ACTIVIDAD),
 ID_ORDEN_TRABAJO NUMBER(19) REFERENCES CT_ORDEN_TRABAJO(ID_ORDEN_TRABAJO),
 ID_REGLA_TIPO NUMBER(19) REFERENCES CT_REGLA_TIPO(ID_REGLA_TIPO),
 ID_REGLA_APLICADA NUMBER(19) REFERENCES CT_REGLA(ID_REGLA));
CREATE TABLE CT_OT_RULE_INCIDENT (
 ID_OT_RULE_INCIDENT NUMBER(19) PRIMARY KEY,
 ID_ORDEN_TRABAJO NUMBER(19) NOT NULL REFERENCES CT_ORDEN_TRABAJO(ID_ORDEN_TRABAJO),
 RULE_NAME VARCHAR2(255) REFERENCES CT_REGLA(NOMBRE),
 RULE_STAGE VARCHAR2(20) NOT NULL, RULE_ERROR_CODE VARCHAR2(100) NOT NULL,
 RULE_ERROR_DETAIL VARCHAR2(1000), RULE_PROCESSED_AT TIMESTAMP(6) NOT NULL,
 STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL, RESOLVED_AT TIMESTAMP(6),
 PROCESSING_ATTEMPT_ID VARCHAR2(36) NOT NULL);
