CREATE SEQUENCE LEGACY.CTS_OT_RULE_INCIDENT
    START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;

CREATE TABLE LEGACY.CT_OT_RULE_INCIDENT (
    ID_OT_RULE_INCIDENT NUMBER(19,0) NOT NULL,
    ID_ORDEN_TRABAJO NUMBER(19,0) NOT NULL,
    RULE_NAME VARCHAR2(255 CHAR),
    RULE_STAGE VARCHAR2(20 CHAR) NOT NULL,
    RULE_ERROR_CODE VARCHAR2(100 CHAR) NOT NULL,
    RULE_ERROR_DETAIL VARCHAR2(1000 CHAR),
    RULE_PROCESSED_AT TIMESTAMP(6) NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    RESOLVED_AT TIMESTAMP(6),
    PROCESSING_ATTEMPT_ID VARCHAR2(36 CHAR) NOT NULL,
    CONSTRAINT PK_OT_RULE_INCIDENT PRIMARY KEY (ID_OT_RULE_INCIDENT),
    CONSTRAINT FK_OT_RULE_INCIDENT_OT FOREIGN KEY (ID_ORDEN_TRABAJO)
        REFERENCES LEGACY.CT_ORDEN_TRABAJO (ID_ORDEN_TRABAJO),
    CONSTRAINT FK_OT_RULE_INCIDENT_RULE FOREIGN KEY (RULE_NAME)
        REFERENCES LEGACY.CT_REGLA (NOMBRE),
    CONSTRAINT CK_OT_RULE_INCIDENT_STATUS CHECK (STATUS IN ('OPEN', 'RESOLVED'))
);

CREATE INDEX LEGACY.IX_OT_RULE_INCIDENT_OT_STATUS
    ON LEGACY.CT_OT_RULE_INCIDENT (ID_ORDEN_TRABAJO, STATUS);
CREATE INDEX LEGACY.IX_OT_RULE_INCIDENT_RULE_STATUS
    ON LEGACY.CT_OT_RULE_INCIDENT (RULE_NAME, STATUS);
CREATE INDEX LEGACY.IX_OT_RULE_INCIDENT_PROCESSED
    ON LEGACY.CT_OT_RULE_INCIDENT (RULE_PROCESSED_AT);
CREATE INDEX LEGACY.IX_OT_RULE_INCIDENT_CODE_STATUS
    ON LEGACY.CT_OT_RULE_INCIDENT (RULE_ERROR_CODE, STATUS);
