CREATE SEQUENCE LEGACY.CTS_RULE_SET START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE LEGACY.CTS_RULE_STAGE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE LEGACY.CTS_RULE_TEMPLATE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE LEGACY.CTS_RULE_DEFINITION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE LEGACY.CTS_RULE_CONDITION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE LEGACY.CTS_RULE_ACTION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;

CREATE TABLE LEGACY.CT_RULE_SET (
    ID_RULE_SET NUMBER(19,0) NOT NULL,
    RULE_SET_NAME VARCHAR2(100 CHAR) NOT NULL,
    RULE_SET_VERSION NUMBER(19,0) NOT NULL,
    STATUS VARCHAR2(20 CHAR) NOT NULL,
    VALIDATED_AT TIMESTAMP(6),
    ACTIVATED_AT TIMESTAMP(6),
    VALIDATION_MESSAGE VARCHAR2(1000 CHAR),
    CONSTRAINT PK_RULE_SET PRIMARY KEY (ID_RULE_SET),
    CONSTRAINT UK_RULE_SET_NAME_VERSION UNIQUE (RULE_SET_NAME, RULE_SET_VERSION),
    CONSTRAINT CK_RULE_SET_VERSION CHECK (RULE_SET_VERSION > 0),
    CONSTRAINT CK_RULE_SET_STATUS CHECK (STATUS IN ('DRAFT', 'VALID', 'ACTIVE', 'RETIRED')),
    CONSTRAINT CK_RULE_SET_ACTIVE_VALID CHECK (STATUS <> 'ACTIVE' OR VALIDATED_AT IS NOT NULL)
);

CREATE UNIQUE INDEX LEGACY.UK_RULE_SET_SINGLE_ACTIVE
    ON LEGACY.CT_RULE_SET (
        CASE WHEN STATUS = 'ACTIVE' THEN RULE_SET_NAME END
    );

CREATE TABLE LEGACY.CT_RULE_STAGE (
    ID_RULE_STAGE NUMBER(19,0) NOT NULL,
    ID_RULE_SET NUMBER(19,0) NOT NULL,
    STAGE_CODE VARCHAR2(20 CHAR) NOT NULL,
    STAGE_ORDER NUMBER(10,0) NOT NULL,
    UNIT_PACKAGE VARCHAR2(255 CHAR) NOT NULL,
    UNIT_NAME VARCHAR2(255 CHAR) NOT NULL,
    ACTIVE CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_RULE_STAGE PRIMARY KEY (ID_RULE_STAGE),
    CONSTRAINT FK_RULE_STAGE_SET FOREIGN KEY (ID_RULE_SET) REFERENCES LEGACY.CT_RULE_SET (ID_RULE_SET),
    CONSTRAINT UK_RULE_STAGE_CODE UNIQUE (ID_RULE_SET, STAGE_CODE),
    CONSTRAINT UK_RULE_STAGE_ORDER UNIQUE (ID_RULE_SET, STAGE_ORDER),
    CONSTRAINT CK_RULE_STAGE_ORDER CHECK (STAGE_ORDER > 0),
    CONSTRAINT CK_RULE_STAGE_ACTIVE CHECK (ACTIVE IN ('S', 'N'))
);

CREATE TABLE LEGACY.CT_RULE_TEMPLATE (
    ID_RULE_TEMPLATE NUMBER(19,0) NOT NULL,
    TEMPLATE_KEY VARCHAR2(100 CHAR) NOT NULL,
    TEMPLATE_VERSION NUMBER(19,0) NOT NULL,
    SHAPE VARCHAR2(100 CHAR) NOT NULL,
    DRL_TEMPLATE CLOB NOT NULL,
    ACTIVE CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_RULE_TEMPLATE PRIMARY KEY (ID_RULE_TEMPLATE),
    CONSTRAINT UK_RULE_TEMPLATE_KEY_VERSION UNIQUE (TEMPLATE_KEY, TEMPLATE_VERSION),
    CONSTRAINT CK_RULE_TEMPLATE_VERSION CHECK (TEMPLATE_VERSION > 0),
    CONSTRAINT CK_RULE_TEMPLATE_ACTIVE CHECK (ACTIVE IN ('S', 'N'))
);

CREATE TABLE LEGACY.CT_RULE_DEFINITION (
    ID_RULE_DEFINITION NUMBER(19,0) NOT NULL,
    ID_RULE_STAGE NUMBER(19,0) NOT NULL,
    ID_RULE_TEMPLATE NUMBER(19,0) NOT NULL,
    RULE_NAME VARCHAR2(255 CHAR) NOT NULL,
    RULE_ORDER NUMBER(10,0) NOT NULL,
    WORK_ORDER_TYPE VARCHAR2(20 CHAR),
    JOB_TYPE VARCHAR2(255 CHAR),
    ACTIVE CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_RULE_DEFINITION PRIMARY KEY (ID_RULE_DEFINITION),
    CONSTRAINT FK_RULE_DEFINITION_STAGE FOREIGN KEY (ID_RULE_STAGE) REFERENCES LEGACY.CT_RULE_STAGE (ID_RULE_STAGE),
    CONSTRAINT FK_RULE_DEFINITION_TEMPLATE FOREIGN KEY (ID_RULE_TEMPLATE) REFERENCES LEGACY.CT_RULE_TEMPLATE (ID_RULE_TEMPLATE),
    CONSTRAINT UK_RULE_DEFINITION_NAME UNIQUE (ID_RULE_STAGE, RULE_NAME),
    CONSTRAINT UK_RULE_DEFINITION_ORDER UNIQUE (ID_RULE_STAGE, RULE_ORDER),
    CONSTRAINT CK_RULE_DEFINITION_ORDER CHECK (RULE_ORDER > 0),
    CONSTRAINT CK_RULE_DEFINITION_ACTIVE CHECK (ACTIVE IN ('S', 'N'))
);

CREATE TABLE LEGACY.CT_RULE_CONDITION (
    ID_RULE_CONDITION NUMBER(19,0) NOT NULL,
    ID_RULE_DEFINITION NUMBER(19,0) NOT NULL,
    POSITION NUMBER(10,0) NOT NULL,
    CONDITION_TYPE VARCHAR2(100 CHAR) NOT NULL,
    OPERATOR VARCHAR2(50 CHAR) NOT NULL,
    CONDITION_VALUE VARCHAR2(1000 CHAR),
    NUMERIC_VALUE NUMBER(19,0),
    CONSTRAINT PK_RULE_CONDITION PRIMARY KEY (ID_RULE_CONDITION),
    CONSTRAINT FK_RULE_CONDITION_DEF FOREIGN KEY (ID_RULE_DEFINITION) REFERENCES LEGACY.CT_RULE_DEFINITION (ID_RULE_DEFINITION),
    CONSTRAINT UK_RULE_CONDITION_POS UNIQUE (ID_RULE_DEFINITION, POSITION),
    CONSTRAINT CK_RULE_CONDITION_POS CHECK (POSITION > 0)
);

CREATE TABLE LEGACY.CT_RULE_ACTION (
    ID_RULE_ACTION NUMBER(19,0) NOT NULL,
    ID_RULE_DEFINITION NUMBER(19,0) NOT NULL,
    POSITION NUMBER(10,0) NOT NULL,
    ACTION_TYPE VARCHAR2(100 CHAR) NOT NULL,
    OLD_ACTIVITY_CODE VARCHAR2(255 CHAR),
    NEW_ACTIVITY_CODE VARCHAR2(255 CHAR),
    CATEGORY VARCHAR2(255 CHAR),
    CONSTRAINT PK_RULE_ACTION PRIMARY KEY (ID_RULE_ACTION),
    CONSTRAINT FK_RULE_ACTION_DEF FOREIGN KEY (ID_RULE_DEFINITION) REFERENCES LEGACY.CT_RULE_DEFINITION (ID_RULE_DEFINITION),
    CONSTRAINT UK_RULE_ACTION_POS UNIQUE (ID_RULE_DEFINITION, POSITION),
    CONSTRAINT CK_RULE_ACTION_POS CHECK (POSITION > 0)
);
