package org.acme.ruleunits.ra2;
unit Ra2Unit;

import org.acme.ruleunits.action.AddActivity;
import org.acme.ruleunits.action.DeactivateAllActivities;
import org.acme.ruleunits.domain.WorkOrderEvaluation;

rule "RA2-test-1"
when
    WorkOrderEvaluation(
        jobType in ("KPVG961", "FM3X635", "FH1X042", "JM5G513")
    ) from entry-point "workOrders"
then
    actions.add(new DeactivateAllActivities("RA2", "RA2-test-1"));
    actions.add(new AddActivity("FG2802", "RA2", "RA2-test-1"));
end
